
# Critical for Cloud Run: listen on PORT env var (defaults to 8080 locally)
server.port=${PORT:8080}

spring.application.name=CUSTOMER-SERVICE

# Database (use env vars in production / Cloud Run)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
# No need to set dialect anymore ? Hibernate auto-detects for MySQL 8+
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Feign client URL (injected later via env var in Cloud Run)
account.service.url=${ACCOUNT_SERVICE_URL:}
logging.level.root=INFO
logging.level.com.bank.customer=DEBUG
management.endpoints.web.exposure.include=health,info

jwt.expiration=86400000

#34.14.211.61
#public ipp
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=60000